version: "3"
services:
 # 关于 nginx 最常见配置的学习
  nginx:
    image: nginx:alpine
    ports:
      - 8000:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/usr/share/nginx/html
  api:
    image: shanyue/whoami
    ports:
      - 8888:3000
  location:
    image: nginx:alpine
    ports:
      - 8100:80
    volumes:
      - ./location.conf:/etc/nginx/conf.d/default.conf
      - .:/usr/share/nginx/html
  location2:
    image: nginx:alpine
    ports:
      - 8120:80
    volumes:
      - ./location2.conf:/etc/nginx/conf.d/default.conf
      - .:/usr/share/nginx/html
  proxy:
    image: nginx:alpine
    ports:
      - 8300:80
    volumes:
      - ./proxy.conf:/etc/nginx/conf.d/default.conf
      - .:/usr/share/nginx/html
  # 如何为 nginx 中添加 module
  # https://github.com/nginxinc/docker-nginx/tree/master/modules
  brotli:
    build:
      context: ./brotli/
      args:
        ENABLED_MODULES: brotli
    ports:
      - 8600:80
    volumes:
      - ./brotli.conf:/etc/nginx/conf.d/default.conf
      - ./brotli-nginx.conf:/etc/nginx/nginx.conf
      - .:/usr/share/nginx/html
  50x:
    image: nginx:alpine
    ports:
      - 8301:80
    volumes:
      - ./50x.conf:/etc/nginx/conf.d/default.conf
      - .:/usr/share/nginx/html


  